title: "Viki's Portfolio"
email: "your-email@example.com"
description: "A personal website for showcasing articles, blogs, projects, and resume."
baseurl: ""
url: "https://<username>.github.io"
theme: "minimal-mistakes-jekyll"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Site settings
paginate: 5
paginate_path: "/page:num/"

# Navigation
header_pages:
  - /articles/
  - /blogs/
  - /projects/
  - /resume/

# Collections
collections:
  articles:
    output: true
    permalink: /articles/:title/
  blogs:
    output: true
    permalink: /blogs/:title/
  projects:
    output: true
    permalink: /projects/:title/
  resume:
    output: true
    permalink: /resume/:title/

# Social media links (optional)
social:
  github: https://github.com/<username>
  linkedin: https://www.linkedin.com/in/<username>
  twitter: https://twitter.com/<username>

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"

# Theme settings
minimal_mistakes_skin: "air"
